### ISSUE TITLE
Optimize two types of featurizer in same config file

### ISSUE THREAD

**Issue by jeiros** [msmbuilder/osprey#137]
Is there a way to alternate between two different types of featurization?

In the config file produced by `osprey skeleton` the featurizer is based on Dihedrals, and then if I understand correctly two types of parameter for that featurizer can be optimized, in:
```
  featurizer__types:
    choices:
      - ['phi', 'psi']
      - ['phi', 'psi', 'chi1']
    type: enum
```

My question is, can I also add another type of featurizer, such as ContactFeaturizer from msmbuilder, for example? Or optimize between two different kinds of clustering algorithm, for instance? What about both things at the same time?

Sorry if what I am suggesting doesn't make sense in hyperparameter optimization.
