### ISSUE TITLE
int64 is not JSON serializable

### ISSUE THREAD

**Issue by jeiros** [msmbuilder/osprey#245]
Hi,

I'm running into an error that I've not seen before. I'm using already-featurized trajectories stored as text numpy arrays, to compare the performance of different featurizers.

Here's the osprey config file:
```yaml
estimator:
    eval: |
        Pipeline([
                ('tica', tICA()),
                ('cluster', MiniBatchKMeans()),
                ('msm', MarkovStateModel(lag_time=100, n_timescales=5, verbose=True)),
        ])
    eval_scope: msmbuilder


strategy:
    name: random

search_space:
  cluster__n_clusters:
    min: 10
    max: 10000
    type: int
    

  tica__lag_time:
    min: 1
    max: 1000
    type: jump
    warp: log
    var_type: int
    num: 10

  tica__commute_mapping:
    choices:
      - True
      - False
    type: enum

  tica__n_components:
    min: 1
    max: 20
    type: int

cv:
  name: shufflesplit
  params:
    n_iter: 5
    test_size: 0.25

dataset_loader:
  name: numpy
  params:
    filenames: ftrajs/*
trials:

  uri: sqlite:///osprey-trials.db

```

And here's the output: https://pastebin.com/gtZxxwEt

I've previously done this kind of workflow, so I don't really know what might've gone wrong.

Best regards,

Juan

**Comment by cxhernandez** [comment]
Hi @jeiros!

Thanks for the report! Could you also share your conda environment? Relevant package versions would be msmbuilder, numpy, sklearn, cython, etc.

**Comment by jeiros** [comment]
Here's a small subset of the data with which the error can be reproduced

[dihedrals.zip](https://github.com/msmbuilder/osprey/files/2260460/dihedrals.zip)

**Comment by jeiros** [comment]
Did you manage to replicate the error?

**Comment by jeiros** [comment]
So I think the problem is in specifying a list of integers in a log warped space:

```yaml
  tica__lag_time:
    min: 1
    max: 1000
    type: jump
    warp: log
    var_type: int
    num: 10
```
I changed it to a `type: int` and now it works.
Perhaps the `int64 is not JSON serializable` error comes from within the Osprey code that deals with the creation of the integers in the log space? Is it maybe using numpy, which stores the integers as the `int64` dtype and that confuses the json package? No idea, since I'm not familiar with osprey's code, it's just a guess.

Let me know what you think
